#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/nokia/B2N

PRODUCT_COPY_FILES += \
    vendor/nokia/B2N/proprietary/vendor/etc/B2N/ncf/aux/ISO200_1280x720.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/B2N/ncf/aux/ISO200_1280x720.ncf \
    vendor/nokia/B2N/proprietary/vendor/etc/B2N/ncf/aux/ISO200_1600x1200.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/B2N/ncf/aux/ISO200_1600x1200.ncf \
    vendor/nokia/B2N/proprietary/vendor/etc/B2N/ncf/aux/ISO200_2688x1512.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/B2N/ncf/aux/ISO200_2688x1512.ncf \
    vendor/nokia/B2N/proprietary/vendor/etc/B2N/ncf/aux/ISO200_3200x2400.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/B2N/ncf/aux/ISO200_3200x2400.ncf \
    vendor/nokia/B2N/proprietary/vendor/etc/B2N/ncf/aux/ISO200_3840x2160.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/B2N/ncf/aux/ISO200_3840x2160.ncf \
    vendor/nokia/B2N/proprietary/vendor/etc/B2N/ncf/aux/ISO200_4032x2016.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/B2N/ncf/aux/ISO200_4032x2016.ncf \
    vendor/nokia/B2N/proprietary/vendor/etc/B2N/ncf/aux/ISO200_4032x3024.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/B2N/ncf/aux/ISO200_4032x3024.ncf \
    vendor/nokia/B2N/proprietary/vendor/etc/B2N/ncf/rear/ISO200_1280x720.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/B2N/ncf/rear/ISO200_1280x720.ncf \
    vendor/nokia/B2N/proprietary/vendor/etc/B2N/ncf/rear/ISO200_1600x1200.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/B2N/ncf/rear/ISO200_1600x1200.ncf \
    vendor/nokia/B2N/proprietary/vendor/etc/B2N/ncf/rear/ISO200_2688x1512.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/B2N/ncf/rear/ISO200_2688x1512.ncf \
    vendor/nokia/B2N/proprietary/vendor/etc/B2N/ncf/rear/ISO200_3200x2400.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/B2N/ncf/rear/ISO200_3200x2400.ncf \
    vendor/nokia/B2N/proprietary/vendor/etc/B2N/ncf/rear/ISO200_3840x2160.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/B2N/ncf/rear/ISO200_3840x2160.ncf \
    vendor/nokia/B2N/proprietary/vendor/etc/B2N/ncf/rear/ISO200_4032x2016.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/B2N/ncf/rear/ISO200_4032x2016.ncf \
    vendor/nokia/B2N/proprietary/vendor/etc/B2N/ncf/rear/ISO200_4032x3024.ncf:$(TARGET_COPY_OUT_VENDOR)/etc/B2N/ncf/rear/ISO200_4032x3024.ncf \
    vendor/nokia/B2N/proprietary/vendor/etc/acdbdata/B2N/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/B2N/Bluetooth_cal.acdb \
    vendor/nokia/B2N/proprietary/vendor/etc/acdbdata/B2N/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/B2N/General_cal.acdb \
    vendor/nokia/B2N/proprietary/vendor/etc/acdbdata/B2N/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/B2N/Global_cal.acdb \
    vendor/nokia/B2N/proprietary/vendor/etc/acdbdata/B2N/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/B2N/Handset_cal.acdb \
    vendor/nokia/B2N/proprietary/vendor/etc/acdbdata/B2N/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/B2N/Hdmi_cal.acdb \
    vendor/nokia/B2N/proprietary/vendor/etc/acdbdata/B2N/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/B2N/Headset_cal.acdb \
    vendor/nokia/B2N/proprietary/vendor/etc/acdbdata/B2N/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/B2N/Speaker_cal.acdb \
    vendor/nokia/B2N/proprietary/vendor/etc/acdbdata/B2N/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/B2N/workspaceFile.qwsp \
    vendor/nokia/B2N/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/nokia/B2N/proprietary/vendor/etc/audio_platform_info_b2n.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_platform_info_b2n.xml \
    vendor/nokia/B2N/proprietary/vendor/etc/camera/calibration_test.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/calibration_test.bin \
    vendor/nokia/B2N/proprietary/vendor/etc/camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_config.xml \
    vendor/nokia/B2N/proprietary/vendor/etc/camera/mgbeautify_1_2_4_model:$(TARGET_COPY_OUT_VENDOR)/etc/camera/mgbeautify_1_2_4_model \
    vendor/nokia/B2N/proprietary/vendor/etc/camera/s5k2l7sa05_b2n_wide_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k2l7sa05_b2n_wide_chromatix.xml \
    vendor/nokia/B2N/proprietary/vendor/etc/camera/s5k3m3sm_b2n_tele_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3m3sm_b2n_tele_chromatix.xml \
    vendor/nokia/B2N/proprietary/vendor/etc/camera/s5k3p8sp_b2n_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3p8sp_b2n_chromatix.xml \
    vendor/nokia/B2N/proprietary/vendor/etc/mixer_paths_b2n.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_paths_b2n.xml \
    vendor/nokia/B2N/proprietary/vendor/etc/sensors/sensor_def_qcomdev_b2.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sensor_def_qcomdev_b2.conf \
    vendor/nokia/B2N/proprietary/vendor/etc/thermal-engine.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine.conf \
    vendor/nokia/B2N/proprietary/vendor/etc/wifi/aoa_cldb_falcon.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/aoa_cldb_falcon.bin \
    vendor/nokia/B2N/proprietary/vendor/etc/wifi/aoa_cldb_swl14.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/aoa_cldb_swl14.bin \
    vendor/nokia/B2N/proprietary/vendor/etc/wifi/bdf/bdwlan_B2N_cal.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bdf/bdwlan_B2N_cal.bin \
    vendor/nokia/B2N/proprietary/vendor/etc/wifi/bdf/bdwlan_def.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bdf/bdwlan_def.bin \
    vendor/nokia/B2N/proprietary/vendor/firmware/TAS2557MSSMono_B2N.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/TAS2557MSSMono_B2N.bin \
    vendor/nokia/B2N/proprietary/vendor/firmware/TAS2557MSSMono_B2N_dvt.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/TAS2557MSSMono_B2N_dvt.bin \
    vendor/nokia/B2N/proprietary/vendor/firmware/a512_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.b01 \
    vendor/nokia/B2N/proprietary/vendor/firmware/a512_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.mdt \
    vendor/nokia/B2N/proprietary/vendor/firmware/goodix_config.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_config.cfg \
    vendor/nokia/B2N/proprietary/vendor/firmware/goodix_config_hlt.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_config_hlt.cfg \
    vendor/nokia/B2N/proprietary/vendor/firmware/goodix_config_oflim.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_config_oflim.cfg \
    vendor/nokia/B2N/proprietary/vendor/firmware/goodix_config_truly.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_config_truly.cfg \
    vendor/nokia/B2N/proprietary/vendor/firmware/goodix_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_firmware.bin \
    vendor/nokia/B2N/proprietary/vendor/firmware/goodix_firmware_hlt.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_firmware_hlt.bin \
    vendor/nokia/B2N/proprietary/vendor/firmware/goodix_firmware_oflim.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_firmware_oflim.bin \
    vendor/nokia/B2N/proprietary/vendor/firmware/goodix_firmware_truly.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_firmware_truly.bin \
    vendor/nokia/B2N/proprietary/vendor/firmware/gxfp3208_b2n.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/gxfp3208_b2n.b00 \
    vendor/nokia/B2N/proprietary/vendor/firmware/gxfp3208_b2n.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/gxfp3208_b2n.b01 \
    vendor/nokia/B2N/proprietary/vendor/firmware/gxfp3208_b2n.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/gxfp3208_b2n.b02 \
    vendor/nokia/B2N/proprietary/vendor/firmware/gxfp3208_b2n.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/gxfp3208_b2n.b03 \
    vendor/nokia/B2N/proprietary/vendor/firmware/gxfp3208_b2n.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/gxfp3208_b2n.b04 \
    vendor/nokia/B2N/proprietary/vendor/firmware/gxfp3208_b2n.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/gxfp3208_b2n.b05 \
    vendor/nokia/B2N/proprietary/vendor/firmware/gxfp3208_b2n.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/gxfp3208_b2n.b06 \
    vendor/nokia/B2N/proprietary/vendor/firmware/gxfp3208_b2n.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/gxfp3208_b2n.b07 \
    vendor/nokia/B2N/proprietary/vendor/firmware/gxfp3208_b2n.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/gxfp3208_b2n.mdt

PRODUCT_PACKAGES += \
    libchromatix_s5k2l7sa05_b2n_wide_4k_preview_3a \
    libchromatix_s5k2l7sa05_b2n_wide_4k_video_3a \
    libchromatix_s5k2l7sa05_b2n_wide_common \
    libchromatix_s5k2l7sa05_b2n_wide_cpp_hfr_60 \
    libchromatix_s5k2l7sa05_b2n_wide_cpp_liveshot \
    libchromatix_s5k2l7sa05_b2n_wide_cpp_preview \
    libchromatix_s5k2l7sa05_b2n_wide_cpp_snapshot \
    libchromatix_s5k2l7sa05_b2n_wide_cpp_video \
    libchromatix_s5k2l7sa05_b2n_wide_cpp_video_4k \
    libchromatix_s5k2l7sa05_b2n_wide_default_preview_3a \
    libchromatix_s5k2l7sa05_b2n_wide_default_video_3a \
    libchromatix_s5k2l7sa05_b2n_wide_hfr_60 \
    libchromatix_s5k2l7sa05_b2n_wide_hfr_60_3a \
    libchromatix_s5k2l7sa05_b2n_wide_postproc \
    libchromatix_s5k2l7sa05_b2n_wide_preview \
    libchromatix_s5k2l7sa05_b2n_wide_snapshot \
    libchromatix_s5k2l7sa05_b2n_wide_snapshot_longexposure \
    libchromatix_s5k2l7sa05_b2n_wide_versions \
    libchromatix_s5k2l7sa05_b2n_wide_video \
    libchromatix_s5k2l7sa05_b2n_wide_video_4k \
    libchromatix_s5k2l7sa05_b2n_wide_zsl_preview_3a \
    libchromatix_s5k2l7sa05_b2n_wide_zsl_video_3a \
    libchromatix_s5k3m3sm_b2n_tele_4k_preview_3a \
    libchromatix_s5k3m3sm_b2n_tele_4k_video_3a \
    libchromatix_s5k3m3sm_b2n_tele_common \
    libchromatix_s5k3m3sm_b2n_tele_cpp_hfr_120 \
    libchromatix_s5k3m3sm_b2n_tele_cpp_hfr_60 \
    libchromatix_s5k3m3sm_b2n_tele_cpp_hfr_90 \
    libchromatix_s5k3m3sm_b2n_tele_cpp_liveshot \
    libchromatix_s5k3m3sm_b2n_tele_cpp_preview \
    libchromatix_s5k3m3sm_b2n_tele_cpp_snapshot \
    libchromatix_s5k3m3sm_b2n_tele_cpp_video \
    libchromatix_s5k3m3sm_b2n_tele_cpp_video_4k \
    libchromatix_s5k3m3sm_b2n_tele_default_preview_3a \
    libchromatix_s5k3m3sm_b2n_tele_default_video \
    libchromatix_s5k3m3sm_b2n_tele_default_video_3a \
    libchromatix_s5k3m3sm_b2n_tele_hfr_120 \
    libchromatix_s5k3m3sm_b2n_tele_hfr_120_3a \
    libchromatix_s5k3m3sm_b2n_tele_hfr_60 \
    libchromatix_s5k3m3sm_b2n_tele_hfr_60_3a \
    libchromatix_s5k3m3sm_b2n_tele_hfr_90 \
    libchromatix_s5k3m3sm_b2n_tele_hfr_90_3a \
    libchromatix_s5k3m3sm_b2n_tele_liveshot \
    libchromatix_s5k3m3sm_b2n_tele_postproc \
    libchromatix_s5k3m3sm_b2n_tele_preview \
    libchromatix_s5k3m3sm_b2n_tele_snapshot \
    libchromatix_s5k3m3sm_b2n_tele_versions \
    libchromatix_s5k3m3sm_b2n_tele_video_4k \
    libchromatix_s5k3m3sm_b2n_tele_zsl_preview_3a \
    libchromatix_s5k3m3sm_b2n_tele_zsl_video_3a \
    libchromatix_s5k3p8sp_b2n_120_hfr \
    libchromatix_s5k3p8sp_b2n_60_hfr \
    libchromatix_s5k3p8sp_b2n_90_hfr \
    libchromatix_s5k3p8sp_b2n_a3_120_hfr \
    libchromatix_s5k3p8sp_b2n_a3_60_hfr \
    libchromatix_s5k3p8sp_b2n_a3_90_hfr \
    libchromatix_s5k3p8sp_b2n_a3_zsl_preview \
    libchromatix_s5k3p8sp_b2n_a3_zsl_video \
    libchromatix_s5k3p8sp_b2n_common \
    libchromatix_s5k3p8sp_b2n_cpp_liveshot \
    libchromatix_s5k3p8sp_b2n_cpp_preview \
    libchromatix_s5k3p8sp_b2n_cpp_snapshot \
    libchromatix_s5k3p8sp_b2n_cpp_snapshot_4m \
    libchromatix_s5k3p8sp_b2n_cpp_video \
    libchromatix_s5k3p8sp_b2n_hfr_120_cpp \
    libchromatix_s5k3p8sp_b2n_hfr_60_cpp \
    libchromatix_s5k3p8sp_b2n_hfr_90_cpp \
    libchromatix_s5k3p8sp_b2n_postproc \
    libchromatix_s5k3p8sp_b2n_preview \
    libchromatix_s5k3p8sp_b2n_snapshot \
    libchromatix_s5k3p8sp_b2n_versions \
    libchromatix_s5k3p8sp_b2n_video \
    libmmcamera_m24c64s_b2n_tele_eeprom \
    libmmcamera_m24c64t_b2n_wide_eeprom \
    libmmcamera_s5k2l7_b2n_wide \
    libmmcamera_s5k3m3sm_b2n_tele \
    libmmcamera_s5k3p8sp_b2n \
    libmmcamera_s5k3p8sp_b2n_gt24c64_eeprom \
    libpn553_fw \
    fingerprint.gxfp3208_b2n \
    libgf_ca_gxfp3208_b2n \
    libgf_hal_gxfp3208_b2n \
    libvendor.goodix.hardware.fingerprint@1.0-service \
    libvendor.goodix.hardware.fingerprint@1.0 \
    libvendor.goodix.hardware.fingerprintextension@1.0 \
    B2N2_TAS2557.ftcfg
